INSERT INTO "Institutions" (
  name,
  "shortName",
  country,
  "countryCode",
  city,
  website,
  "contactEmail",
  status,
  description,
  "createdAt",
  "updatedAt"
) VALUES
  (
    'Universitatea din București',
    'UB',
    'România',
    'RO',
    'București',
    'https://unibuc.ro',
    'admitere@unibuc.ro',
    'active',
    'Universitate publică multidisciplinară, folosită ca instituție activă în fluxul de admitere UniTrack.',
    now(),
    now()
  ),
  (
    'Universitatea Tehnică din Cluj-Napoca',
    'UTCN',
    'România',
    'RO',
    'Cluj-Napoca',
    'https://www.utcluj.ro',
    'admitere@utcluj.ro',
    'active',
    'Instituție tehnică pentru programe de calculatoare, automatică și inginerie.',
    now(),
    now()
  ),
  (
    'Universitatea Politehnica București',
    'UPB',
    'România',
    'RO',
    'București',
    'https://upb.ro',
    'admitere@upb.ro',
    'active',
    'Instituție tehnică pentru programe de inginerie, automatică și calculatoare.',
    now(),
    now()
  ),
  (
    'Universitatea Babeș-Bolyai',
    'UBB',
    'România',
    'RO',
    'Cluj-Napoca',
    'https://www.ubbcluj.ro',
    'admitere@ubbcluj.ro',
    'active',
    'Instituție multidisciplinară cu programe de informatică, economie și științe sociale.',
    now(),
    now()
  ),
  (
    'Delft University of Technology',
    'TU Delft',
    'Olanda',
    'NL',
    'Delft',
    'https://www.tudelft.nl',
    'admissions@tudelft.nl',
    'active',
    'Universitate tehnică internațională pentru computer science și engineering.',
    now(),
    now()
  ),
  (
    'KU Leuven',
    'KU',
    'Belgia',
    'BE',
    'Leuven',
    'https://www.kuleuven.be',
    'admissions@kuleuven.be',
    'active',
    'Universitate europeană cu programe de engineering și artificial intelligence.',
    now(),
    now()
  ),
  (
    'University of Edinburgh',
    'UoE',
    'Marea Britanie',
    'GB',
    'Edinburgh',
    'https://www.ed.ac.uk',
    'admissions@ed.ac.uk',
    'active',
    'Instituție internațională cu programe de informatics și artificial intelligence.',
    now(),
    now()
  )
ON CONFLICT (name) DO UPDATE SET
  "shortName" = EXCLUDED."shortName",
  country = EXCLUDED.country,
  "countryCode" = EXCLUDED."countryCode",
  city = EXCLUDED.city,
  website = EXCLUDED.website,
  "contactEmail" = EXCLUDED."contactEmail",
  status = EXCLUDED.status,
  description = EXCLUDED.description,
  "updatedAt" = now();
